# Site wide configuration

title: Michael Levy
description: "Computational social-environmental science"
logo: myLogo.png
teaser: site_teaser.png  
locale: en_US
url: http://michaellevy.name
name: Michael Levy

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rougify
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Michael Levy
  email: malevy@ucdavis.edu
  twitter: ucdlevy
  google:
    ad-client: 
    ad-slot: 
    ads: false
  bio: "PhD Candidate in Environmental Science & Policy at UC Davis."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: michaellevy

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
